#include "templategenerator.h"

#include <QRegularExpression>
#include <QSet>
#include <QTextStream>

void TemplateGenerator::setSnippets(const QList<Snippet> &snippets)
{
    m_snippets = snippets;
}

QString TemplateGenerator::generate() const
{
    QSet<QString>  seen;
    QList<QString> includes;

    for (const Snippet &s : m_snippets) {
        for (const QString &inc : extractIncludes(s.code)) {
            if (!seen.contains(inc)) {
                seen.insert(inc);
                includes.append(inc);
            }
        }
    }

    QString out;
    QTextStream ts(&out);

    ts << "// Auto-generated by CP Toolkit — TemplateGenerator\n\n";

    for (const QString &inc : includes)
        ts << inc << "\n";

    ts << "\nusing namespace std;\n";

    for (const Snippet &s : m_snippets) {
        const QString ns   = toNamespaceId(s.title);
        const QString body = stripIncludes(s.code).trimmed();

        if (body.isEmpty())
            continue;

        ts << "\n// --- " << s.title << " ---\n";
        ts << "namespace " << ns << " {\n\n";
        ts << body << "\n\n";
        ts << "} // namespace " << ns << "\n";
    }

    ts << "\nint main()\n{\n";
    ts << "    // TODO: write your solution here\n\n";
    ts << "    return 0;\n}\n";

    return out;
}

QList<QString> TemplateGenerator::extractIncludes(const QString &code) const
{
    static const QRegularExpression re(
        QStringLiteral(R"(^\s*#\s*include\s*[<"][^>"]+[>"])"),
        QRegularExpression::MultilineOption);

    QList<QString> result;
    auto it = re.globalMatch(code);
    while (it.hasNext())
        result.append(it.next().captured(0).trimmed());

    return result;
}

QString TemplateGenerator::stripIncludes(const QString &code) const
{
    static const QRegularExpression re(
        QStringLiteral(R"(^\s*#\s*include\s*[<"][^>"]+[>"][^\n]*\n?)"),
        QRegularExpression::MultilineOption);

    QString stripped = code;
    stripped.remove(re);
    return stripped;
}

QString TemplateGenerator::toNamespaceId(const QString &title) const
{
    QString id = title.toLower();

    static const QRegularExpression nonAlnum(QStringLiteral("[^a-z0-9]+"));
    id.replace(nonAlnum, QStringLiteral("_"));

    while (id.startsWith(QLatin1Char('_')))
        id.remove(0, 1);
    while (id.endsWith(QLatin1Char('_')))
        id.chop(1);

    if (!id.isEmpty() && id.front().isDigit())
        id.prepend(QLatin1Char('_'));

    return id.isEmpty() ? QStringLiteral("snippet") : id;
}